name: Build and Deploy Development
on:
  push:
    branches:
      - 'dev'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the codebase from github.
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0\
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: kalamunadev1
          SRC_PATH: "wordpress/"
          # Deploy Options
          SCRIPT: wp-content/themes/kalapress-theme/bin/wpe/post-deploy.sh