name: Build and Deploy Production
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the codebase from github.
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0\
      # Dependencies and compiled assets are commited directly in repository.
      #- name: Use Node.js
      #  uses: actions/setup-node@v2
      #- name: Check Node Version
      #  run: node -v
      # Install composer dependencies
      #- name: Composer Process
      #  run: cd wordpress/wp-content/themes/crate && composer install -n
      # Install node modules and build theme.
      #- name: Node Process
      #  run: npm install --prefix wordpress/wp-content/themes/crate && npm run compile:css --prefix wordpress/wp-content/themes/kalapress-theme
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          # WPE_ENV: foodwise
          # SRC_PATH: "wordpress/"
